#!/usr/bin/env bash

source .docksal/utils/header
source .docksal/utils/dropdown

selections=(
    "run"
    "init"
    "exit"
)

choose_from_menu " Please make a choice:" selected_choice "${selections[@]}"
echo "Selected choice: $selected_choice"


case $selected_choice in
    "run")
        fin start
        fin url
        ;;
    "init")
        source .docksal/utils/init
        ;;
    "exit")
        ;;
esac